name: Android CI

on: [push]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Gradle Cache
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches/
          key: ${{ runner.OS }}-gradle-cache

      - name: Gradle Wraper Cache
        uses: actions/cache@v1
        with:
          path: ~/.gradle/wrapper/
          key: ${{ runner.OS }}-gradle-wraper-cache

      - name: Android Build Cache
        uses: actions/cache@v1
        with:
          path: ~/.android/build-cache
          key: ${{ runner.OS }}-android-cache

      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Download and Install SDK
        run: |
          mkdir /tmp/.androidSdk
          wget --quiet --output-document=android-sdk.zip https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip
          sudo unzip -d ~/.androidSdk android-sdk.zip > /dev/null
          export ANDROID_HOME="/tmp/.androidSdk"

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Sync Gradle
        run: ./gradlew clean dependencies

      - name: Build the project
        run: ./gradlew build

      - name: Test
        run: ./gradlew testDebugUnitTest

      - name: Integrated Tests
        uses: malinskiy/action-android/emulator-run-cmd@release/0.0.5
        with:
          cmd: ./gradlew connectedAndroidTest
          api: 25
          tag: default
          abi: x86